package org.fedoraproject.japi.checker.web.model;

import com.googlecode.japi.checker.ClassDataLoader;
import com.googlecode.japi.checker.model.ClassData;

/**
 * Class generated by hbm2java
 */
public class Class extends ClassData implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private int id;

    // private Set<Class> classes = new HashSet<Class>(0); // TODO inner classes

    public Class() {
        super();
    }

    public Class(ClassDataLoader<?> loader, ClassData owner, int access,
            String name, String superName, String[] interfaces, int version) {
        super(loader, owner, access, name, superName, interfaces, version);
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

}
