package org.fedoraproject.japi.checker.web.model;

// Generated Feb 27, 2013 2:23:31 PM by Hibernate Tools 3.4.0.CR1

import com.googlecode.japi.checker.DifferenceType;
import com.googlecode.japi.checker.model.JavaItem;

/**
 * Difference generated by hbm2java
 */
public class Difference extends com.googlecode.japi.checker.Difference implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private ReleasesComparison releasesComparison;

	public Difference() {
	}

	public Difference(ReleasesComparison releasesComparison,
			JavaItem reference, JavaItem new_, DifferenceType differenceType, Object... args) {
		super(reference, new_, differenceType, args);
		this.releasesComparison = releasesComparison;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ReleasesComparison getReleasesComparison() {
		return this.releasesComparison;
	}

	public void setReleasesComparison(ReleasesComparison releasesComparison) {
		this.releasesComparison = releasesComparison;
	}

}
