package org.fedoraproject.japi.checker.web.model;

import com.googlecode.japi.checker.model.ClassData;
import com.googlecode.japi.checker.model.MethodData;

/**
 * Method generated by hbm2java
 */
public class Method extends MethodData implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private int id;

    public Method() {
    }

    public Method(ClassData owner, int access, String name, String descriptor,
            String[] exceptions) {
        super(owner, access, name, descriptor, exceptions);
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
