package org.fedoraproject.japi.checker.web.model;

// Generated Feb 27, 2013 2:23:31 PM by Hibernate Tools 3.4.0.CR1

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.googlecode.japi.checker.ClassDataLoader;
import com.googlecode.japi.checker.JarReader;
import com.googlecode.japi.checker.utils.AntPatternMatcher;

/**
 * Release generated by hbm2java
 */
public class Release implements java.io.Serializable, ClassDataLoader<Class> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Library library;
	private String name;
	private List<Class> classes = new ArrayList<Class>(0);

	public Release() {
	}

	public Release(Library library, String name) {
		this.library = library;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Library getLibrary() {
		return this.library;
	}

	public void setLibrary(Library library) {
		this.library = library;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Class> getClasses() {
		return this.classes;
	}

	public void setClasses(List<Class> classes) {
		this.classes = classes;
	}
	
	protected void read(File file) throws IOException {
		JarReader<Class> reader;
        reader = new JarReader<Class>(file, this, Class.class, Field.class, Method.class, TypeParameter.class);
        reader.read();
        this.setClasses(reader.getClasses());
	}

	// TODO this method is useless, try to use read(String file) instead
	public void read(URI uri) throws IOException {
        if ("file".equals(uri.getScheme())) {
            read(new File(uri.getPath()));
        } else {
            throw new IOException("Unsupported scheme: " + uri.getScheme());
        }		
	}

	@Nullable
	public Class fromName(String name) {
		// TODO rework classes to Map and find class on the application level
		return null;
	}

	@Nonnull
	public List<Class> getClasses(@Nonnull URI uri) {
		// TODO Auto-generated method stub
		return null;
	}

	@Nonnull
	public List<Class> getClasses(@Nonnull URI uri,
			@Nonnull List<AntPatternMatcher> includes,
			@Nonnull List<AntPatternMatcher> excludes) {
		// TODO Auto-generated method stub
		return null;
	}

}
