package org.fedoraproject.japi.checker.web.model;

import com.googlecode.japi.checker.model.TypeParameterData;

/**
 * TypeParameter generated by hbm2java
 */
public class TypeParameter extends TypeParameterData implements
        java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private int id;

    public TypeParameter() {
    }

    public TypeParameter(String name) {
        super(name);
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

}
